version: '3'
services:
  local-db:
    image: library/mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      TZ: Asia/Seoul
    platform: linux/x86_64
